/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import com.formdev.flatlaf.json.ParseException;
import com.itextpdf.text.Document;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import control.AdmDatos;
import control.DetallePedidoJpaController;
import control.PedidoJpaController;
import control.ProductoJpaController;
import control.TrabajadorJpaController;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import modelo.DatosTablaRetiro;
import modelo.DatosTablaVenta;
import modelo.DetallePedido;
import modelo.MTablaRetiro;
import modelo.MTablaVenta;
import modelo.ModeloTicket;
import modelo.Pedido;
import modelo.Producto;
import modelo.Trabajador;

/**
 *
 * @author Hp EliteBook
 */
public class InterfazCajero extends javax.swing.JDialog {

    private DetallePedido detallePedido;
    private List<DetallePedido> detallePedidos;
    private DetallePedidoJpaController cDetallePedido;
    private List<DetallePedido> productosComprados = new ArrayList<>();
    private ProductoJpaController cProducto;
    private ArrayList<DatosTablaVenta> datosVentas = new ArrayList<>();
    private MTablaVenta modTabVenta;
    private BigDecimal Total = new BigDecimal(0), subTotal = new BigDecimal(0), monto = new BigDecimal(0), cantidadPagada = new BigDecimal(0);
    private final BigDecimal IVA_PORCENTAJE = new BigDecimal("0.16");
    private String TipoPago, nombreCajero;
    private List<String> tiposPagos = new ArrayList<>();
    private List<BigDecimal> pagosParciales = new ArrayList<>();
    private BigDecimal efectivo = new BigDecimal(0);
    private BigDecimal cupon = new BigDecimal(0);
    private BigDecimal credito = new BigDecimal(0);
    private BigDecimal debito = new BigDecimal(0);
    private BigDecimal vale = new BigDecimal(0);
    private BigDecimal totalVentas = new BigDecimal(0);
    private int Retiros = 0, RetirosAux = 0;
    private Document doc = new Document();
    private String nombreArchivo = "ticket.pdf";  // Se sobrescribirá si ya existe
    private List<Trabajador> trabajadores;
    private TrabajadorJpaController cTrabajador;
    private boolean autorizado = false;
    private int aux = 0;

    /**
     * Creates new form InterfazCajero
     */
    public InterfazCajero(java.awt.Frame parent, boolean modal, String usuarioElegido) {
        super(parent, modal);
        initComponents();
        cProducto = new ProductoJpaController(AdmDatos.getEntityManagerFactory());
        //productos = cProducto.findProductoEntities();
        cDetallePedido = new DetallePedidoJpaController(AdmDatos.getEntityManagerFactory());
        detallePedidos = cDetallePedido.findDetallePedidoEntities();
        nombreCajero = usuarioElegido;
        cTrabajador = new TrabajadorJpaController(AdmDatos.getEntityManagerFactory());
        trabajadores = cTrabajador.findTrabajadorEntities();
        efectivo = efectivo.setScale(2, RoundingMode.HALF_UP);
        cupon = cupon.setScale(2, RoundingMode.HALF_UP);
        credito = credito.setScale(2, RoundingMode.HALF_UP);
        debito = debito.setScale(2, RoundingMode.HALF_UP);
        vale = vale.setScale(2, RoundingMode.HALF_UP);
        inabilitar();
        TablaLista();
        limpiarArchivo("retiros.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextProducto = new javax.swing.JTextField();
        PanelBotones = new javax.swing.JPanel();
        InicioPanel = new javax.swing.JPanel();
        BotonIniciarVenta = new javax.swing.JButton();
        BotonRetiro = new javax.swing.JButton();
        BotonSupervisor = new javax.swing.JButton();
        BotonSalirInicio = new javax.swing.JButton();
        PanelVenta = new javax.swing.JPanel();
        EfectivoVenta = new javax.swing.JButton();
        DebitoVenta = new javax.swing.JButton();
        CreditoVenta = new javax.swing.JButton();
        CuponVenta = new javax.swing.JButton();
        SalirVenta = new javax.swing.JButton();
        ValeVenta = new javax.swing.JButton();
        PanelSupervisor = new javax.swing.JPanel();
        ReporteParcial = new javax.swing.JButton();
        ReporteFinal = new javax.swing.JButton();
        UltimaTransaccion = new javax.swing.JButton();
        SalirSupervisor = new javax.swing.JButton();
        PanelRetiro = new javax.swing.JPanel();
        AgregarRetiro = new javax.swing.JButton();
        ConsultarRetiro = new javax.swing.JButton();
        RegresarRetiro = new javax.swing.JButton();
        PanelDetalles = new javax.swing.JPanel();
        PanelDetalleVentas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaPago = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        PanelDetalleRetiros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TMil = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TQuinientos = new javax.swing.JTextField();
        TDoscientos = new javax.swing.JTextField();
        TCien = new javax.swing.JTextField();
        TCincuenta = new javax.swing.JTextField();
        TVeinte = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        LTotalRetiro = new javax.swing.JLabel();
        GenerarRetiro = new javax.swing.JButton();
        PanelConsultarRetiros = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaRetiros = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        EliminarRetiro = new javax.swing.JButton();
        ModificarRetiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 14)); // NOI18N
        jLabel1.setText("Zapateria MiChingon");

        TextProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextProductoActionPerformed(evt);
            }
        });

        PanelBotones.setLayout(new java.awt.CardLayout());

        BotonIniciarVenta.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonIniciarVenta.setText("Iniciar Venta");
        BotonIniciarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarVentaActionPerformed(evt);
            }
        });

        BotonRetiro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonRetiro.setText("Retiro");
        BotonRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRetiroActionPerformed(evt);
            }
        });

        BotonSupervisor.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonSupervisor.setText("Menu Supervisor");
        BotonSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSupervisorActionPerformed(evt);
            }
        });

        BotonSalirInicio.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonSalirInicio.setText("Salir");
        BotonSalirInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioPanelLayout = new javax.swing.GroupLayout(InicioPanel);
        InicioPanel.setLayout(InicioPanelLayout);
        InicioPanelLayout.setHorizontalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonIniciarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSalirInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InicioPanelLayout.setVerticalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonIniciarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonSalirInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBotones.add(InicioPanel, "InicioPanel");

        EfectivoVenta.setText("Efectivo");
        EfectivoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfectivoVentaActionPerformed(evt);
            }
        });

        DebitoVenta.setText("Targeta de Debito");
        DebitoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitoVentaActionPerformed(evt);
            }
        });

        CreditoVenta.setText("Targeta de Credito");
        CreditoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditoVentaActionPerformed(evt);
            }
        });

        CuponVenta.setText("Cupon");
        CuponVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuponVentaActionPerformed(evt);
            }
        });

        SalirVenta.setText("Regresar");
        SalirVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirVentaActionPerformed(evt);
            }
        });

        ValeVenta.setText("Vale por Devolucion");
        ValeVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValeVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVentaLayout = new javax.swing.GroupLayout(PanelVenta);
        PanelVenta.setLayout(PanelVentaLayout);
        PanelVentaLayout.setHorizontalGroup(
            PanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreditoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DebitoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ValeVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CuponVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EfectivoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelVentaLayout.setVerticalGroup(
            PanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(EfectivoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CuponVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ValeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DebitoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreditoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SalirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        PanelBotones.add(PanelVenta, "PanelVenta");

        ReporteParcial.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ReporteParcial.setText("Reporte Parcial");
        ReporteParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteParcialActionPerformed(evt);
            }
        });

        ReporteFinal.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ReporteFinal.setText("Reporte Final");
        ReporteFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteFinalActionPerformed(evt);
            }
        });

        UltimaTransaccion.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        UltimaTransaccion.setText("Ultima Transaccion");
        UltimaTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimaTransaccionActionPerformed(evt);
            }
        });

        SalirSupervisor.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        SalirSupervisor.setText("Regresar");
        SalirSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirSupervisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSupervisorLayout = new javax.swing.GroupLayout(PanelSupervisor);
        PanelSupervisor.setLayout(PanelSupervisorLayout);
        PanelSupervisorLayout.setHorizontalGroup(
            PanelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSupervisorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReporteParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReporteFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UltimaTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalirSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSupervisorLayout.setVerticalGroup(
            PanelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSupervisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReporteParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReporteFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UltimaTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SalirSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBotones.add(PanelSupervisor, "PanelSupervisor");

        AgregarRetiro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        AgregarRetiro.setText("Generar Retiro");
        AgregarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarRetiroActionPerformed(evt);
            }
        });

        ConsultarRetiro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ConsultarRetiro.setText("Consultar Retiros");
        ConsultarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarRetiroActionPerformed(evt);
            }
        });

        RegresarRetiro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        RegresarRetiro.setText("Regresar");
        RegresarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarRetiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRetiroLayout = new javax.swing.GroupLayout(PanelRetiro);
        PanelRetiro.setLayout(PanelRetiroLayout);
        PanelRetiroLayout.setHorizontalGroup(
            PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRetiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRetiroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ConsultarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRetiroLayout.createSequentialGroup()
                        .addGroup(PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegresarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelRetiroLayout.setVerticalGroup(
            PanelRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRetiroLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(AgregarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConsultarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegresarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        PanelBotones.add(PanelRetiro, "PanelRetiro");

        PanelDetalles.setLayout(new java.awt.CardLayout());

        AreaPago.setColumns(20);
        AreaPago.setRows(5);
        AreaPago.setText("Subtotal \n\n--------------------------------------------------------------------------------------------------------------------------\nTotal a pagar:");
        jScrollPane2.setViewportView(AreaPago);

        TablaProducto.setForeground(new java.awt.Color(204, 204, 204));
        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProducto);

        javax.swing.GroupLayout PanelDetalleVentasLayout = new javax.swing.GroupLayout(PanelDetalleVentas);
        PanelDetalleVentas.setLayout(PanelDetalleVentasLayout);
        PanelDetalleVentasLayout.setHorizontalGroup(
            PanelDetalleVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        PanelDetalleVentasLayout.setVerticalGroup(
            PanelDetalleVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetalleVentasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelDetalles.add(PanelDetalleVentas, "PanelDetalleVentas");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("$1000");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("$500");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("$200");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("$100");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("$20");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("$50");

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Generar Nuevo Retiro");

        TMil.setText("0");
        TMil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TMilFocusLost(evt);
            }
        });
        TMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TMilActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("------------------------------------------------------------");

        TQuinientos.setText("0");
        TQuinientos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TQuinientosFocusLost(evt);
            }
        });
        TQuinientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TQuinientosActionPerformed(evt);
            }
        });

        TDoscientos.setText("0");
        TDoscientos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TDoscientosFocusLost(evt);
            }
        });
        TDoscientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TDoscientosActionPerformed(evt);
            }
        });

        TCien.setText("0");
        TCien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TCienFocusLost(evt);
            }
        });
        TCien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCienActionPerformed(evt);
            }
        });

        TCincuenta.setText("0");
        TCincuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TCincuentaFocusLost(evt);
            }
        });
        TCincuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCincuentaActionPerformed(evt);
            }
        });

        TVeinte.setText("0");
        TVeinte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TVeinteFocusLost(evt);
            }
        });
        TVeinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TVeinteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Total:");

        LTotalRetiro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LTotalRetiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTotalRetiro.setText("$");

        GenerarRetiro.setText("Generar");
        GenerarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarRetiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDetalleRetirosLayout = new javax.swing.GroupLayout(PanelDetalleRetiros);
        PanelDetalleRetiros.setLayout(PanelDetalleRetirosLayout);
        PanelDetalleRetirosLayout.setHorizontalGroup(
            PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetalleRetirosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TMil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TVeinte, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TQuinientos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TDoscientos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(221, 221, 221))
            .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel10)
                        .addGap(31, 31, 31)
                        .addComponent(LTotalRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GenerarRetiro))
                    .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel9)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        PanelDetalleRetirosLayout.setVerticalGroup(
            PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleRetirosLayout.createSequentialGroup()
                        .addComponent(TMil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TQuinientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TDoscientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TCien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TVeinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(LTotalRetiro))
                    .addComponent(GenerarRetiro))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        PanelDetalles.add(PanelDetalleRetiros, "PanelDetalleRetiros");

        TablaRetiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaRetiros);

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel12.setText("Retiros Realizados");

        EliminarRetiro.setText("Eliminar");
        EliminarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarRetiroActionPerformed(evt);
            }
        });

        ModificarRetiro.setText("Modificar");
        ModificarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarRetiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelConsultarRetirosLayout = new javax.swing.GroupLayout(PanelConsultarRetiros);
        PanelConsultarRetiros.setLayout(PanelConsultarRetirosLayout);
        PanelConsultarRetirosLayout.setHorizontalGroup(
            PanelConsultarRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultarRetirosLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(EliminarRetiro)
                .addGap(79, 79, 79)
                .addComponent(ModificarRetiro)
                .addGap(0, 182, Short.MAX_VALUE))
            .addGroup(PanelConsultarRetirosLayout.createSequentialGroup()
                .addGroup(PanelConsultarRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConsultarRetirosLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelConsultarRetirosLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelConsultarRetirosLayout.setVerticalGroup(
            PanelConsultarRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultarRetirosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(PanelConsultarRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarRetiro)
                    .addComponent(ModificarRetiro))
                .addGap(22, 22, 22))
        );

        PanelDetalles.add(PanelConsultarRetiros, "PanelConsultarRetiros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextProducto))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void TablaLista() {
        TablaProducto.setModel(new MTablaVenta(new ArrayList<>()));
        TablaProducto.getTableHeader().setReorderingAllowed(false);
        TablaProducto.getTableHeader().setResizingAllowed(false);
        TablaProducto.setShowGrid(true); // Asegúrate que las líneas se muestren
        TablaProducto.setGridColor(new Color(45, 45, 45)); // Color gris claro (puedes cambiarlo)
        TablaProducto.getColumnModel().getColumn(0).setPreferredWidth(240); // Descripción
        TablaProducto.getColumnModel().getColumn(1).setPreferredWidth(80);  // Precio
        TablaProducto.getColumnModel().getColumn(2).setPreferredWidth(70);  // Cantidad
        TablaProducto.getColumnModel().getColumn(3).setPreferredWidth(90);  // Descuento
        TablaProducto.getColumnModel().getColumn(4).setPreferredWidth(120); // Subtotal

    }

    public void inabilitar() {
        TextProducto.setEditable(false);
        AreaPago.setEditable(false);
    }

    public void Habilitar() {
        TextProducto.setEditable(true);
    }

    public void asignarPago(BigDecimal cantidad, String tipoPago) {
        switch (tipoPago) {
            case "Efectivo":
                efectivo = efectivo.add(cantidad);
                break;
            case "Cupon": ;
                cupon = cupon.add(cantidad);
                break;
            case "Credito":
                credito = credito.add(cantidad);
                break;
            case "Debito":
                debito = debito.add(cantidad);
                break;
            case "Vale":
                vale = vale.add(cantidad);
                break;
        }
    }

    public void modificarTextArea() {
        Total = subTotal;
        AreaPago.setText("Subtotal\t\t\t\t\t\t    $" + subTotal + "\n"
                + "\n"
                + "--------------------------------------------------------------------------------------------------------------------------\n"
                + "Total a pagar:\t\t\t\t\t\t   $" + Total);
    }

    public void GenerarTicket(List<String> pagos) {
        //new PanelTicket(null, true, pagos,pagosParciales, nombreCajero, datosVentas, Total, monto, cantidadPagada);
        ModeloTicket ticket = new ModeloTicket(pagos, pagosParciales, nombreCajero, datosVentas, Total, monto, cantidadPagada);
        ticket.generarYMostrarTicket("ticket.pdf");
        cantidadPagada = new BigDecimal(0);
    }

    public void Cobro(String tipoPago) {
        if (TablaProducto.getRowCount() == 0) {
            return;
        }

        montoPagado panelAuxiliar = new montoPagado(null, true, subTotal);
        panelAuxiliar.setVisible(true);
        monto = panelAuxiliar.getMonto();
        BigDecimal pagoAuxiliar = monto;
        cantidadPagada = cantidadPagada.add(monto);

        if (cantidadPagada.compareTo(Total) < 0) {
            asignarPago(monto, tipoPago);
            subTotal = subTotal.subtract(monto);
            AreaPago.setText("Subtotal\t\t\t\t\t\t    $" + subTotal + "\n"
                    + "\n"
                    + "--------------------------------------------------------------------------------------------------------------------------\n"
                    + "Total a pagar:\t\t\t\t\t\t   $" + Total);
            tiposPagos.add(tipoPago);
            pagosParciales.add(pagoAuxiliar);
            return;
        } else {
            monto = BigDecimal.ZERO;
            monto = cantidadPagada.subtract(Total);
        }

        tiposPagos.add(tipoPago);
        pagosParciales.add(pagoAuxiliar);
        totalVentas = totalVentas.add(Total);

        asignarPago(subTotal, tipoPago);

        TipoPago = tipoPago;
        GenerarTicket(tiposPagos);

        tiposPagos.clear();
        AreaPago.setText("Subtotal\n"
                + "\n"
                + "--------------------------------------------------------------------------------------------------------------------------\n"
                + "Total a pagar:");
        datosVentas.clear();
        modTabVenta = new MTablaVenta(datosVentas);
        TablaProducto.setModel(modTabVenta);
        TextProducto.setText("");
        CardLayout cl = (CardLayout) (PanelBotones.getLayout());
        cl.show(PanelBotones, "InicioPanel"); // o "inicio"
        Habilitar();

        Total = BigDecimal.ZERO;
        subTotal = BigDecimal.ZERO;
        TextProducto.setEditable(false);
    }

    private void BotonIniciarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarVentaActionPerformed
        detallePedidos = cDetallePedido.findDetallePedidoEntities();
        CardLayout cl = (CardLayout) (PanelBotones.getLayout());
        cl.show(PanelBotones, "PanelVenta"); // o "inicio"
        Habilitar();
    }//GEN-LAST:event_BotonIniciarVentaActionPerformed

    private void BotonSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSupervisorActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (PanelBotones.getLayout());
        cl.show(PanelBotones, "PanelSupervisor"); // o "inicio"
    }//GEN-LAST:event_BotonSupervisorActionPerformed

    private void BotonRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRetiroActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (PanelBotones.getLayout());
        cl.show(PanelBotones, "PanelRetiro"); // o "inicio"
    }//GEN-LAST:event_BotonRetiroActionPerformed

    private void ReporteParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteParcialActionPerformed
        // TODO add your handling code here:
        List<String> ListaAuxiliar = new ArrayList<>();
        ListaAuxiliar.add(nombreCajero);
        ListaAuxiliar.add(efectivo + "");
        ListaAuxiliar.add(debito + "");
        ListaAuxiliar.add(credito + "");
        ListaAuxiliar.add(cupon + "");
        ListaAuxiliar.add(vale + "");
        ListaAuxiliar.add(Retiros + "");
        ListaAuxiliar.add(totalVentas + "");
        ListaAuxiliar.add("X");
        new PanelReporteVenta(null, true, ListaAuxiliar).setVisible(true);

    }//GEN-LAST:event_ReporteParcialActionPerformed

    private void ReporteFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteFinalActionPerformed
        // TODO add your handling code here:
        List<String> ListaAuxiliar = new ArrayList<>();
        ListaAuxiliar.add(nombreCajero);
        ListaAuxiliar.add(efectivo + "");
        ListaAuxiliar.add(debito + "");
        ListaAuxiliar.add(credito + "");
        ListaAuxiliar.add(cupon + "");
        ListaAuxiliar.add(vale + "");
        ListaAuxiliar.add(Retiros + "");
        ListaAuxiliar.add(totalVentas + "");
        ListaAuxiliar.add(" Z");

        new PanelReporteVenta(null, true, ListaAuxiliar).setVisible(true);

        efectivo = BigDecimal.ZERO;
        debito = BigDecimal.ZERO;
        credito = BigDecimal.ZERO;
        cupon = BigDecimal.ZERO;
        vale = BigDecimal.ZERO;
        Retiros = 0;
        totalVentas = BigDecimal.ZERO;
    }//GEN-LAST:event_ReporteFinalActionPerformed

    private void UltimaTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimaTransaccionActionPerformed
        // TODO add your handling code here:
        try {
            File archivo = new File("C:\\Users\\Hp EliteBook\\OneDrive\\Documents\\Instituto Tecnologico de Oaxaca\\6 Semestre\\Ingeniería de Software\\MiChingon\\ticket.pdf");  // Ruta del PDF ya creado
            if (archivo.exists()) {
                Desktop.getDesktop().open(archivo);  // Abre con el visor de PDF predeterminado
            } else {
                System.out.println("El archivo no existe.");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UltimaTransaccionActionPerformed

    private void AgregarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarRetiroActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (PanelDetalles.getLayout());
        cl.show(PanelDetalles, "PanelDetalleRetiros"); // o "inicio"
        System.out.println(PanelDetalles.getSize());
    }//GEN-LAST:event_AgregarRetiroActionPerformed

    private void ConsultarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarRetiroActionPerformed
        // TODO add your handling code here:
        cargarRetirosEnTabla(TablaRetiros);
        CardLayout cl = (CardLayout) (PanelDetalles.getLayout());
        cl.show(PanelDetalles, "PanelConsultarRetiros"); // o "inicio"
        System.out.println(PanelDetalles.getSize());
    }//GEN-LAST:event_ConsultarRetiroActionPerformed

    public void cargarRetirosEnTabla(JTable tabla) {
        String ruta = "retiros.txt";
        List<DatosTablaRetiro> listaRetiros = new ArrayList<>();

        try ( BufferedReader br = new BufferedReader(new FileReader(ruta))) {
            String linea;

            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(", ");  // separa por tabulación
                if (datos.length == 3) {
                    String nombre = datos[0];
                    int monto = Integer.parseInt(datos[1]);

                    // Intenta parsear la fecha
                    Date fecha;
                    try {
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                        fecha = sdf.parse(datos[2]);
                    } catch (ParseException e) {
                        fecha = new Date(); // Si falla, asigna fecha actual como fallback
                    } catch (java.text.ParseException ex) {
                        fecha = new Date();
                    }
                    DatosTablaRetiro retiro = new DatosTablaRetiro(nombre, monto, LocalDate.now());
                    listaRetiros.add(retiro);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Cargar modelo personalizado
        MTablaRetiro modelo = new MTablaRetiro(listaRetiros);
        tabla.setModel(modelo);
    }

    public void eliminarRetiro(JTable tabla, int filaSeleccionada) {
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila.");
            return;
        }

        MTablaRetiro modelo = (MTablaRetiro) tabla.getModel();
        DatosTablaRetiro retiroAEliminar = modelo.getRetiroEnFila(filaSeleccionada);

        // 1. Eliminar de la lista en memoria
        modelo.eliminarRetiro(filaSeleccionada);

        // 2. Reescribir el archivo sin ese retiro
        reescribirArchivoDesdeModelo(modelo);

        // 3. Actualizar la tabla
        tabla.setModel(modelo);

    }

    public void reescribirArchivoDesdeModelo(MTablaRetiro modelo) {
        String ruta = "retiros.txt";
        try ( BufferedWriter bw = new BufferedWriter(new FileWriter(ruta))) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            for (DatosTablaRetiro retiro : modelo.getListaRetiros()) {
                String linea = retiro.getNombreCajero() + ", " + retiro.getMonto() + ", " + sdf.format(retiro.getFecha());
                bw.write(linea);
                bw.newLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void TextProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextProductoActionPerformed
        // TODO add your handling code here:
        detallePedidos = cDetallePedido.findDetallePedidoEntities();
        String entrada = TextProducto.getText().trim();
        if (!entrada.isEmpty()) {
            try {
                int productoIngresado = Integer.parseInt(entrada);
                boolean encontrado = false;
                for (DetallePedido dp : detallePedidos) {
                    BigInteger b = BigInteger.valueOf(aux);
                    if (dp.getIdProducto().getIdProducto() == productoIngresado && dp.getCantidad().compareTo(b) > 0
                            && !dp.getIdPedido().getEstado().equals("entregado")) {
                        DatosTablaVenta dtv = new DatosTablaVenta(dp.getIdProducto());
                        datosVentas.add(dtv);
                        subTotal = subTotal.add(dtv.getSubtotal());
                        encontrado = true;
                        productosComprados.add(dp);
                        aux++;
                        break; // Producto encontrado, salimos del ciclo                        
                    }
                }
                if (!encontrado){
                    JOptionPane.showMessageDialog(null, "Pedido no registrado.");
                }
                TextProducto.setText("");
                modTabVenta = new MTablaVenta(datosVentas);
                TablaProducto.setModel(modTabVenta);
                modificarTextArea();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "ID de producto inválido.");
            }
        }
    }//GEN-LAST:event_TextProductoActionPerformed

    private void BotonSalirInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirInicioActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            ((JDialog) SwingUtilities.getWindowAncestor(BotonSalirInicio)).dispose();
        }

    }//GEN-LAST:event_BotonSalirInicioActionPerformed

    private void SalirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirVentaActionPerformed
        CardLayout cl = (CardLayout) (PanelBotones.getLayout());
        cl.show(PanelBotones, "InicioPanel"); // o "inicio"
        TextProducto.setEditable(false);
    }//GEN-LAST:event_SalirVentaActionPerformed

    private void SalirSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirSupervisorActionPerformed
        CardLayout cl = (CardLayout) (PanelBotones.getLayout());
        cl.show(PanelBotones, "InicioPanel"); // o "inicio"
    }//GEN-LAST:event_SalirSupervisorActionPerformed

    private void RegresarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarRetiroActionPerformed
        CardLayout cl = (CardLayout) (PanelBotones.getLayout());
        cl.show(PanelBotones, "InicioPanel"); // o "inicio"
        cl = (CardLayout) (PanelDetalles.getLayout());
        cl.show(PanelDetalles, "PanelDetalleVentas");
    }//GEN-LAST:event_RegresarRetiroActionPerformed

    private void EfectivoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfectivoVentaActionPerformed
        Cobro("Efectivo");
    }//GEN-LAST:event_EfectivoVentaActionPerformed

    private void CuponVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuponVentaActionPerformed
        Cobro("Cupon");
    }//GEN-LAST:event_CuponVentaActionPerformed

    private void DebitoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitoVentaActionPerformed
        Cobro("Debito");
    }//GEN-LAST:event_DebitoVentaActionPerformed

    private void CreditoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditoVentaActionPerformed
        Cobro("Credito");
    }//GEN-LAST:event_CreditoVentaActionPerformed

    private void ValeVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValeVentaActionPerformed
        Cobro("Vale");
    }//GEN-LAST:event_ValeVentaActionPerformed

    private void TMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMilActionPerformed
        calcularTotalRetiro();
    }//GEN-LAST:event_TMilActionPerformed

    private void TQuinientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TQuinientosActionPerformed
        calcularTotalRetiro();
    }//GEN-LAST:event_TQuinientosActionPerformed

    private void TDoscientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TDoscientosActionPerformed
        calcularTotalRetiro();
    }//GEN-LAST:event_TDoscientosActionPerformed

    private void TCienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCienActionPerformed
        calcularTotalRetiro();
    }//GEN-LAST:event_TCienActionPerformed

    private void TCincuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCincuentaActionPerformed
        calcularTotalRetiro();
    }//GEN-LAST:event_TCincuentaActionPerformed

    private void TVeinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TVeinteActionPerformed
        calcularTotalRetiro();
    }//GEN-LAST:event_TVeinteActionPerformed

    private void GenerarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarRetiroActionPerformed
        // TODO add your handling code here:
        boolean valido = false;
        List<Integer> datosRetiro = new ArrayList<>();
        valido = AgregarTotalRetiro();
        if (!valido) {
            return;
        }

        datosRetiro.add(Integer.parseInt(TMil.getText()));
        datosRetiro.add(Integer.parseInt(TQuinientos.getText()));
        datosRetiro.add(Integer.parseInt(TDoscientos.getText()));
        datosRetiro.add(Integer.parseInt(TCien.getText()));
        datosRetiro.add(Integer.parseInt(TCincuenta.getText()));
        datosRetiro.add(Integer.parseInt(TVeinte.getText()));
        datosRetiro.add(RetirosAux);
        System.out.println(RetirosAux + "");
        limpiarRetiro();
        new PanelRetiro(null, true, datosRetiro, nombreCajero).setVisible(true);
        Retiros += RetirosAux;
        LTotalRetiro.setText("$");
    }//GEN-LAST:event_GenerarRetiroActionPerformed

    private void EliminarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarRetiroActionPerformed
        // 3. Validación de selección en tabla
        int filaSeleccionada = TablaRetiros.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila.");
            return;
        }

        if (!validarGerente()) {
            return;
        }

        // 4. Confirmación antes de eliminar
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar este retiro?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        // 5. Eliminar el retiro
        MTablaRetiro modelo = (MTablaRetiro) TablaRetiros.getModel();
        DatosTablaRetiro retiroAEliminar = modelo.getRetiroEnFila(filaSeleccionada);
        Retiros -= retiroAEliminar.getMonto(); // Ajustar total
        modelo.eliminarRetiro(filaSeleccionada);
        reescribirArchivoDesdeModelo(modelo);
        TablaRetiros.setModel(modelo);

        JOptionPane.showMessageDialog(null, "Retiro eliminado correctamente.");

    }//GEN-LAST:event_EliminarRetiroActionPerformed

    public boolean validarGerente() {
        boolean validar = false;
        // 1. Obtener la contraseña del gerente
        String contraseñaGerente = null;

        for (Trabajador t : trabajadores) {
            if (t.getRol().equalsIgnoreCase("Gerente")) {
                contraseñaGerente = t.getPassword();
                break;
            }
        }

        if (contraseñaGerente == null) {
            JOptionPane.showMessageDialog(null, "No se encontró al gerente en el sistema.");
            return validar;
        }
        // 2. Validar contraseña
        JPasswordField campoContrasena = new JPasswordField();
        int opcion = JOptionPane.showConfirmDialog(null, campoContrasena, "Contraseña Gerente", JOptionPane.OK_CANCEL_OPTION);

        if (opcion != JOptionPane.OK_OPTION) {
            return validar;
        }

        String ingresada = new String(campoContrasena.getPassword());
        if (!ingresada.equals(contraseñaGerente)) {
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta.");
            return validar;
        }
        validar = true;
        return validar;
    }

    private void ModificarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarRetiroActionPerformed
        // 1. Validar que se haya seleccionado una fila
        int filaSeleccionada = TablaRetiros.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila.");
            return;
        }
        // 2. Obtener el retiro seleccionado
        MTablaRetiro modelo = (MTablaRetiro) TablaRetiros.getModel();
        DatosTablaRetiro retiroSeleccionado = modelo.getRetiroEnFila(filaSeleccionada);

        if (!validarGerente()) {
            return;
        }
        DatosTablaRetiro original = modelo.getRetiroEnFila(filaSeleccionada);
        // 3. Abrir el panel de edición con los datos
        InterfazEditarRetiro panel = new InterfazEditarRetiro(null, true, retiroSeleccionado);
        panel.setVisible(true);
        DatosTablaRetiro resultado = panel.getRetiroEditado();
        if (resultado != null) {
            Retiros = Retiros - original.getMonto() + resultado.getMonto(); // Reajustar total
            modelo.actualizarRetiro(filaSeleccionada, resultado);
            reescribirArchivoDesdeModelo(modelo);
            TablaRetiros.setModel(modelo);
        }

    }//GEN-LAST:event_ModificarRetiroActionPerformed

    private void TMilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TMilFocusLost
        calcularTotalRetiro();
    }//GEN-LAST:event_TMilFocusLost

    private void TQuinientosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TQuinientosFocusLost
        calcularTotalRetiro();
    }//GEN-LAST:event_TQuinientosFocusLost

    private void TDoscientosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TDoscientosFocusLost
        calcularTotalRetiro();
    }//GEN-LAST:event_TDoscientosFocusLost

    private void TCienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TCienFocusLost
        calcularTotalRetiro();
    }//GEN-LAST:event_TCienFocusLost

    private void TCincuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TCincuentaFocusLost
        calcularTotalRetiro();
    }//GEN-LAST:event_TCincuentaFocusLost

    private void TVeinteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TVeinteFocusLost
        calcularTotalRetiro();
    }//GEN-LAST:event_TVeinteFocusLost

    public boolean AgregarTotalRetiro() {
        boolean validar = false;
        BigDecimal NuevoRetiro = new BigDecimal(RetirosAux);
        BigDecimal RetiroGuardado = new BigDecimal(Retiros);
        NuevoRetiro = NuevoRetiro.add(RetiroGuardado);
        if (RetirosAux > 0 && NuevoRetiro.compareTo(efectivo) < 0) {
            validar = true;
        } else {
            JOptionPane.showMessageDialog(null, "Reporte Invalido");
        }
        return validar;
    }

    public void limpiarArchivo(String ruta) {
        try ( PrintWriter writer = new PrintWriter(ruta)) {
            // No escribimos nada para vaciar el archivo
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void calcularTotalRetiro() {
        try {
            RetirosAux = 0;
            RetirosAux += Integer.parseInt(TMil.getText()) * 1000;     // Billetes de 1000
            RetirosAux += Integer.parseInt(TQuinientos.getText()) * 500;      // Billetes de 500
            RetirosAux += Integer.parseInt(TDoscientos.getText()) * 200;      // Billetes de 200
            RetirosAux += Integer.parseInt(TCien.getText()) * 100;      // Billetes de 100
            RetirosAux += Integer.parseInt(TCincuenta.getText()) * 50;       // Billetes de 50
            RetirosAux += Integer.parseInt(TVeinte.getText()) * 20;       // Billetes de 20
            LTotalRetiro.setText("$ " + RetirosAux);
        } catch (Exception e) {
            limpiarRetiro();
        }
    }

    public void limpiarRetiro() {
        TMil.setText(0 + "");
        TQuinientos.setText(0 + "");
        TDoscientos.setText(0 + "");
        TCien.setText(0 + "");
        TCincuenta.setText(0 + "");
        TVeinte.setText(0 + "");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            FlatMacDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

        
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazCajero dialog = new InterfazCajero(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarRetiro;
    private javax.swing.JTextArea AreaPago;
    private javax.swing.JButton BotonIniciarVenta;
    private javax.swing.JButton BotonRetiro;
    private javax.swing.JButton BotonSalirInicio;
    private javax.swing.JButton BotonSupervisor;
    private javax.swing.JButton ConsultarRetiro;
    private javax.swing.JButton CreditoVenta;
    private javax.swing.JButton CuponVenta;
    private javax.swing.JButton DebitoVenta;
    private javax.swing.JButton EfectivoVenta;
    private javax.swing.JButton EliminarRetiro;
    private javax.swing.JButton GenerarRetiro;
    private javax.swing.JPanel InicioPanel;
    private javax.swing.JLabel LTotalRetiro;
    private javax.swing.JButton ModificarRetiro;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelConsultarRetiros;
    private javax.swing.JPanel PanelDetalleRetiros;
    private javax.swing.JPanel PanelDetalleVentas;
    private javax.swing.JPanel PanelDetalles;
    private javax.swing.JPanel PanelRetiro;
    private javax.swing.JPanel PanelSupervisor;
    private javax.swing.JPanel PanelVenta;
    private javax.swing.JButton RegresarRetiro;
    private javax.swing.JButton ReporteFinal;
    private javax.swing.JButton ReporteParcial;
    private javax.swing.JButton SalirSupervisor;
    private javax.swing.JButton SalirVenta;
    private javax.swing.JTextField TCien;
    private javax.swing.JTextField TCincuenta;
    private javax.swing.JTextField TDoscientos;
    private javax.swing.JTextField TMil;
    private javax.swing.JTextField TQuinientos;
    private javax.swing.JTextField TVeinte;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JTable TablaRetiros;
    private javax.swing.JTextField TextProducto;
    private javax.swing.JButton UltimaTransaccion;
    private javax.swing.JButton ValeVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
